In [2]:
import pandas as pd

df = pd.read_csv('data/sales.csv')

# 数据清洗
# 1.缺失值处理
# df.isnull() # 查看缺失值
# df.isnull().sum() # 查看缺失值个数
# # 删除缺失值(需要赋值给df)
# df = df.dropna() # (默认删除包含缺失值的行， axis=0)需要指定 axis=1 删除包含缺失值的列
# 填充缺失值
# 已有数值不变
df = df.fillna('--') # (默认填充0，需要指定填充的值)
df = df.ffill() # 填充上一行的值
df = df.bfill() # 填充下一行的值
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19     --  微信支付  2025/06/02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [8]:
# 2.重复值处理
# df.duplicated() # 查看重复值(默认查看所有列)
df.duplicated(subset=['订单号']) # 查看重复值(subset指定查看的列)
# df.duplicated().sum() # 查看重复值个数
# 删除重复值(需要赋值给df)
df.drop_duplicates(subset=['订单号']) # (默认删除重复值的行， axis=0)需要指定 axis=1 删除重复值的列
df.drop_duplicates(subset=['订单号'],keep='last') # keep 'last'保留最后一个，’first‘保留第一个

            订单号  产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品   枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品   海苔     5   29     天津    现金  2025-06-01
3    6823473137    食品   面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品   薯片     2   19     --  微信支付  2025/06/02
5    5897064217    图书   字帖     4   29     广州    现金  2025-06-02
..          ...   ...  ...   ...  ...    ...   ...         ...
995  5887473055    图书   小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品   坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装   围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品   果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品   蜂蜜     5   89     西安   银行卡  2026-03-20

[999 rows x 8 columns]

In [18]:
# 3.异常值处理
# 查看异常值
df[df['单价'] < 0]

# 删除异常值
# df.drop(df[df['单价'] < 0].index)

# 修复异常值
df['单价'] = df['单价'].abs()
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19     --  微信支付  2025/06/02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [19]:
# 数据格式处理
df['订单日期'] = df['订单日期'].str.replace('/', '-')
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19     --  微信支付  2025-06-02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]